eureka:
  client:
    # 注册服务中心
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false # 不使用 Eureka 进行服务注册
    fetch-registry: false       # 不要在本地缓存注册信息
  # 如果客户端启动过于频繁，eureka 对服务可用未知，他就会默认为服务可用，因此开发环境关闭这个功能，生产环境一定关闭
  server:
    enable-self-preservation: false
#  instance:
#    # 主机的别名
#    hostname: peer1
spring:
  application:
    name: server-eureka
server:
  port: 8761